// Get OpenAI API
const { Configuration, OpenAIApi } = require("openai");

// Setup Dotenv
require("dotenv").config();

// Configure OpenAPI API
const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});

const openai = new OpenAIApi(configuration);

// Setup DaVinci
const {
  Client,
  GatewayIntentBits,
  ActivityType,
  EmbedBuilder,
} = require("discord.js");
const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
  ],
});

const personality = process.env.PERSONALITY;

// Start Message
client.on("ready", () => {
  console.log(
    `DaVinci has successfully started. Logged in as ${client.user.tag}! Version: ${process.env.VERSION}, running on ${client.guilds.cache.size} servers.`
  );

  client.user.setActivity("/help | nouhi.dev/davinci", {
    type: ActivityType.Playing,
  });
});

// Commands Handling
client.on("interactionCreate", async (interaction) => {
  if (!interaction.isChatInputCommand()) return;

  if (interaction.commandName === "ask") {
    user_prompt = personality + interaction.options.getString("prompt");
    try {
      await interaction.reply("Processing your request...");
      const result = await get_ai_response(user_prompt);
      await interaction.editReply(result.trim());
    } catch {
      console.log("An internal error occurred.");
    }
  }

  if (interaction.commandName === "info") {
    interaction.reply({ embeds: [infoEmbed] });
  }

  if (interaction.commandName === "help") {
    interaction.reply({ embeds: [helpEmbed] });
  }
});

// Returns a Response generated by OpenAI
async function get_ai_response(prompt) {
  const response = await openai.createCompletion({
    model: "text-davinci-003",
    prompt: prompt,
    temperature: 0.0,
    max_tokens: 2000,
    top_p: 1,
    frequency_penalty: 0.5,
    presence_penalty: 0,
    stop: ['"""'],
  });

  return response.data.choices[0].text;
}

// Info Embed
const infoEmbed = new EmbedBuilder()
  .setColor(0xff8086)
  .setTitle("DaVinci v" + `${process.env.VERSION}`)
  .setURL("https://nouhi.dev/davinci/")
  .setAuthor({
    name: "/info",
    iconURL: "https://nouhi.dev/assets/pfp_hd.png",
    url: "https://nouhi.dev/davinci",
  })
  .setDescription(
    "The DaVinci discord bot utilizes the OpenAI API to provide natural language processing capabilities within Discord."
  )
  .setThumbnail("https://nouhi.dev/assets/pfp_hd.png")
  .setTimestamp()
  .setFooter({
    text: "Created by nouhidev | nouhi#0439",
    iconURL: "https://nouhi.dev/assets/pfp_hd.png",
  });

// Help Embed
const helpEmbed = new EmbedBuilder()
  .setColor(0xff8086)
  .setTitle("How to use DaVinci:")
  .setURL("https://nouhi.dev/davinci/")
  .setAuthor({
    name: "/help",
    iconURL: "https://nouhi.dev/assets/pfp_hd.png",
  })
  .setDescription(
    "You can use the following commands to interact with DaVinci:"
  )
  .setThumbnail("https://nouhi.dev/assets/pfp_hd.png")
  .addFields(
    { name: "/ask prompt:", value: "Ask a question", inline: true },
    { name: "/info", value: "Displays this message", inline: true },
    { name: "/help", value: "Displays a guide", inline: true }
  )
  .setTimestamp()
  .setFooter({
    text: "Created by nouhidev | nouhi#0439",
    iconURL: "https://nouhi.dev/assets/pfp_hd.png",
  });

// Login DaVinci
client.login(process.env.DISCORD_KEY);
